services:
  db:
    image: postgres:16
    container_name: go_backend_db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5436:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
